---
- include_role:
    name: firewall
    private: yes
  vars:
    firewall_port_list:
      - { destination_port: 6844, protocol: tcp }
      - { destination_port: 48879, protocol: tcp }
      - { destination_port: 56063, protocol: tcp }
      - { destination_port: 14002, protocol: tcp }
      - { destination_port: 14003, protocol: tcp }
      - { destination_port: 14004, protocol: tcp }
      - { destination_port: 14006, protocol: tcp }
      - { destination_port: 31415, protocol: tcp }

- name: Install ksh
  package:
    name: ksh
    state: present

- name: Add spectrum user
  user:
    name: '{{ install_owner }}'

- name: Check for existing SRAdmin install
  stat:
    path: /sw/SPECTRUM/SRAdmin
  register: srad_stat

- name: Check for existing SS install
  stat:
    path: '{{ installation_path }}'
  register: ss_stat

- name: Extract Spectrum Installer
  unarchive:
    dest: /tmp
    src: '{{ ssmajor_installer_path }}'
  when: not ss_stat.stat.exists
 
- name: Install SRAdmin
  command: /tmp/sdic/linux/srainstall.bin -i silent
  when: not srad_stat.stat.exists

- name: Copy distributed install host file
  template:
    src: distinst.host_inst.j2
    dest: /distinst.host_inst
  when: not ss_stat.stat.exists

- name:  Copy distributed install password file
  template:
    src: distinst.pass.j2
    dest: /distinst.pass
  when: not ss_stat.stat.exists

- name: Copy hosts file
  copy:
    src: /etc/hosts
    dest: /etc/hosts
    force: yes
    owner: root
    group: root
    mode: 0644
  when: not ss_stat.stat.exists

- name: Install SpectroSERVER
  command: /tmp/sdic/sdiclinux.exe -h /distinst.host_inst -p /distinst.pass -accept
  when: not ss_stat.stat.exists

- name: Add OneClick to the .hostrc
  shell: echo "" >> {{ installation_path }}/.hostrc ; echo + >> {{ installation_path }}/.hostrc
  when: not ss_stat.stat.exists

- name: Start the SpectroSERVER
  command: '{{ installation_path }}/bin/startSS.pl'
  become: true
  become_user: '{{ install_owner }}'
 
