---
- include_role:
    name: firewall
    private: yes
  vars:
    firewall_port_list:
      - { destination_port: 8300, protocol: tcp }
      - { destination_port: 8301, protocol: tcp }
      - { destination_port: 8302, protocol: tcp }
      - { destination_port: 8500, protocol: tcp }
      - { destination_port: 8500, protocol: udp }

- name: Check for existing Consul Server install
  stat:
    path: '{{ installation_path }}'
  register: consul_server_stat

- name: Copy installer properties
  template:
    src: installer.response.j2
    dest: /consul-server.response
  when: not consul_server_stat.stat.exists

- name: Copy Consul Server installer
  copy:
    src: '{{ consul_installer_path }}'
    dest: /installConsul.bin
    mode: 0700
    remote_src: '{{ consul_installer_remote_src }}'
  when: not consul_server_stat.stat.exists

- name: Install Consul Server
  command: /installConsul.bin -i silent -f /consul-server.response
  when: not consul_server_stat.stat.exists

