# /etc/ansible/configurations/nfa_install.yml
---
- name: Install NFA Playbook
  hosts: nfa
  become_method: runas
  tasks:
  - name: Check for existing NFA install
    win_stat:
      path: D:\CA\NFA 
    register: nfa_stat

  - name: Copy hosts file
    win_copy: 
     src: /etc/hosts
     dest: C:\Windows\System32\drivers\etc\hosts
     force: yes
    when: not nfa_stat.stat.exists

  - name: Copy installer response files for NFA
    win_copy:
     src: /root/netops-ansible/roles/nfa/templates/
     dest: D:\installers\nfa\bits\
    when: not nfa_stat.stat.exists

  - name: Copy NFA AD installer files
    win_copy:
     src: '{{ nfaad_installer_path }}'
     dest: D:\installers\nfa\bits\ADSetup.exe
    when: not nfa_stat.stat.exists

  - name: Copy NFA Harvester installer files
    win_copy:
     src: '{{ nfah_installer_path }}'
     dest: D:\installers\nfa\bits\NFHarvesterSetup.exe
    when: not nfa_stat.stat.exists

  - name: Copy NFA Console installer files
    win_copy:
     src: '{{ nfac_installer_path }}'
     dest: D:\installers\nfa\bits\RAConsoleSetup.exe
    when: not nfa_stat.stat.exists

  - name: Install NFA Harvester
    become: yes
    become_user: administrator
    win_package:
     path: d:\installers\nfa\bits\NFHarvesterSetup.exe
     creates_path: D:\CA\NFA
     product_id: NFA Harvester
     arguments: '-i silent -f NFHarvester_installer.properties'
     state: present
    when: not nfa_stat.stat.exists
     
  - name: Install NFA Console
    become: yes
    become_user: administrator
    win_package:
     path: d:\installers\nfa\bits\RAConsoleSetup.exe
     product_id: NFA Console
     arguments: '-i silent -f RAConsole_installer.properties'
     state: present
    when: not nfa_stat.stat.exists
     
  - name: Wait on Reboot
    wait_for: timeout=90
    delegate_to: localhost
    when: not nfa_stat.stat.exists
     
  - name: Install NFA Anomaly Detector
    become: yes
    become_user: administrator
    win_package:
     path: d:\installers\nfa\bits\ADSetup.exe
     product_id: NFA Anomaly Detector
     arguments: '-i silent -f AD_installer.properties'
     state: present
    when: not nfa_stat.stat.exists

...
