---
- name: Check for existing UIM install
  stat:
    path: '{{ installation_path }}'
  register: uim_stat

- name: Copy distributed install host file
  template:
    src: uim.host_inst.j2
    dest: /uim.host_inst
  when: not uim_stat.stat.exists

- name: Install UIM Primary Hub / UMP
  command: '{{ distinst_installer_path }} -h /distinst.host_inst -p /distinst.pass -accept' ?????????????????????
  when: not ss_stat.stat.exists

- name: Start the UIM Primary Hub / UMP
  command: '{{ installation_path }}/bin/startSS.pl'  ????????????????????????????
  become: true
  become_user: '{{ install_owner }}'
 
